### ISSUE TITLE
ArcGIS Pro crashes when clicking Launch ArcRhino button

### ISSUE THREAD

**Issue by eap23** [nicoazel/ArcRhino#1]
Hi,

after I added the extracted folder from `ArcRhino_Addin_Install.zip` to _ArcGIS Pro_ via the _Add-In Manager_, I click on _Add-In_ > _Launch ArcRhino_ and _ArcGIS Pro_ crashes (see screenshots):
![grafik](https://user-images.githubusercontent.com/26528531/93865819-22c13400-fcc7-11ea-9589-08d6d5ee2a8c.png)
![grafik](https://user-images.githubusercontent.com/26528531/93866098-88152500-fcc7-11ea-904f-b63a0bb52c53.png)

Any suggestions? Versions conflicts, etc.

I have _Rhino 7 WIP_ running on my _Windows 10_ machine.

Thanks,
Eduard

**Comment by nicoazel** [comment]
Hi Eduard, 

I tested the plugin this morning on a new machine and had no errors in importing geometry from ArcGIS into Rhino. 
I was using ArcGIS Pro 2.6.1 and Rhino 7 WIP 2020-9-22

I dont have any insights into what is causing the crash, running the plugin alongside visual studio would help provide errors messages that would assist in troubleshooting. 

My only guess might be that, because it crashed when the plugin button is clicked, it may be having trouble finding and opening rhino 7 on your machine. When you click the plugin button it generates an arcgis pane and then launches Rhino, so finding and opening rhino seems the more likely source of the error.

**Comment by eap23** [comment]
Thanks @nicoazel for checking!
I found out that Rhino 7 WIP does not work anymore since McNeel changed their licensing policy.
Will have to fix this beforehand and give it a try again.
